name: Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Linter, Jest, TSC Build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      hoverfly:
        image: spectolabs/hoverfly:latest
        ports:
        - 8500/tcp
        - 8888/tcp

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Run linter
      run: npm run lint
    - name: Run tsc build
      run: npm run build
    - name: Run jest tests
      run: npm run test
      env:
        HOVERFLY_ADMIN_URL: http://localhost:${{ job.services.hoverfly.ports[8888] }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: jest-report
        path: /tmp/test-report.html
        retention-days: 30
